ExtractMethod refactoring done on BlockGenus.java
mikaelhg/openblocks pull request #27
Opened 2022-03-27 22:05 UTC by NavyaJayapal

One refactoring performed

2022-03-28 18:04 UTC, mikaelhg commented
Good. If you're willing to do a little bit more work, you could make all of the method parameters `final`, as well as those variables declared inside the method which do not change after their declaration.

2022-03-28 23:34 UTC, mikaelhg requested changes

2022-03-31 18:11 UTC, mikaelhg commented
I'll go ahead and merge this, and we'll do the further improvements as follow-ups, so that you can get your course points.

2022-03-31 18:12 UTC, merged

2022-03-31 19:15 UTC, NavyaJayapal commented
Hi Mikhael,

Sorry for the late response. It was a very hectic week for me.
I will do further follow ups as I find myself having good time refactoring.

Thank u for accepting my pull request. Will catch up with you with more changes in the following weeks.

Regards,
Navya Jayapal.
________________________________
From: Mikael Gueck ***@***.***>
Sent: Thursday, March 31, 2022 3:12:23 PM
To: mikaelhg/openblocks ***@***.***>
Cc: Navya Jayapal ***@***.***>; Assign ***@***.***>
Subject: Re: [mikaelhg/openblocks] ExtractMethod refactoring done on BlockGenus.java (PR #27)

CAUTION: The Sender of this email is not from within Dalhousie.

Merged #27<https://github.com/mikaelhg/openblocks/pull/27> into master.

—
Reply to this email directly, view it on GitHub<https://github.com/mikaelhg/openblocks/pull/27#event-6346153265>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYK6HELGKMY4PUFPELIFNPTVCXTIPANCNFSM5RZL7HLA>.
You are receiving this because you were assigned.Message ID: ***@***.***>